openapi: 3.0.0
info:
  title: Insight People managment API Docs
  description: Insight People managment API Docs...
  version: 1.0.0
paths:
  /people/{id}:
    get:
      summary: Returns a person.
      description: Returns a person...
      tags:
        - People
      parameters:
        - name: id
          in: path
          description: id of the person.
          schema:
            type: string
      responses:
        "200": # status code
          description: a person.
          content:
            application/json:
              schema:
                type: object
        "400": # status code
          description: Invalid id.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: not found.
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: delete a person.
      description: delete a person...
      tags:
        - People
      parameters:
        - name: id
          in: path
          description: id of the person.
          schema:
            type: string
      responses:
        "200": # status code
          description: A person.
          content:
            application/json:
              schema:
                type: object
        "400": # status code
          description: Invalid id.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: not found.
          content:
            application/json:
              schema:
                type: object
    put:
      summary: update a person.
      description: update a person...
      tags:
        - People
      parameters:
        - name: id
          in: path
          description: id of the person.
          schema:
            type: string
      responses:
        "400": # status code
          description: invalid id.
          content:
            application/json:
              schema:
                type: object
        "200": # status code
          description: A person.
          content:
            application/json:
              schema:
                type: object
        "201": # status code
          description: A person.
          content:
            application/json:
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                role:
                  type: string
                wage: 
                  type: string
                phone:
                  type: string
                birthday: 
                  type: string
                shifts:
                  type: array 
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                      startTime:
                        type: string
                      endTime:
                        type: string
                      taskId:
                        type: string
                      area:
                        type: string
  /people:
    post:
      summary: Create a person.
      description: Create a person...
      tags:
        - People
      responses:
        "201": # status code
          description: A person.
          content:
            application/json:
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              # User:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                role:
                  type: string
                wage: 
                  type: string
                phone:
                  type: string
                birthday: 
                  type: string
                shifts:
                  type: array 
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                      startTime: 
                        type: string
                      endTime: 
                        type: string
                      taskId: 
                        type: string
                      area:
                        type: string 
  /bulk/people/{ids}:
    get:
      summary: Returns people by ids.
      description: Returns persons by ids...
      tags:
        - Bulk people
      parameters:
        - name: ids
          in: path
          description: ids of the people. It should look like `5ca45de909520ac243514afa,5ca45de909520ac243514aff`
          schema:
            type: array
              items:
                type: string
      responses:
        "200": # status code
          description: List of people.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400": # status code
          description: Invalid ids.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: all ids not found.
          content:
            application/json:
              schema:
                type: object  
  /bulk/people:
    get:
      summary: Returns people list.
      description: Returns persons by ids...
      tags:
        - Bulk people
      responses:
        "200": # status code
          description: List of people.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404": # status code
          description: no people found.
          content:
            application/json:
              schema:
                type: object  
  /task/{id}:
    get:
      summary: Returns a task.
      description: Returns a task...
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: id of the task.
          schema:
            type: string
      responses:
        "200": # status code
          description: a task.
          content:
            application/json:
              schema:
                type: object
        "400": # status code
          description: Invalid id.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: not found.
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: delete a task.
      description: delete a task...
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: id of the task.
          schema:
            type: string
      responses:
        "200": # status code
          description: A task.
          content:
            application/json:
              schema:
                type: object
        "400": # status code
          description: Invalid id.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: not found.
          content:
            application/json:
              schema:
                type: object
    put:
      summary: update a task.
      description: update a task...
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          description: id of the task.
          schema:
            type: string
      responses:
        "400": # status code
          description: invalid id.
          content:
            application/json:
              schema:
                type: object
        "200": # status code
          description: A task.
          content:
            application/json:
              schema:
                type: object
        "201": # status code
          description: A task.
          content:
            application/json:
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                postPerson:
                  type: string
                assignTo:
                  type: array
                dueDate: 
                  type: string  
  /task:
    post:
      summary: Create a task.
      description: Create a task...
      tags:
        - Tasks
      responses:
        "201": # status code
          description: A Task.
          content:
            application/json:
              schema:
                type: object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                postPerson:
                  type: string
                assignTo:
                  type: array 
                    items:
                      type: string 
                dueDate: 
                  type: string 
  /bulk/task/{ids}:
    get:
      summary: Returns tasks by ids.
      description: Returns tasks by ids...
      tags:
        - Bulk tasks
      parameters:
        - name: ids
          in: path
          description: ids of the tasks. It should look like `5ca45de909520ac243514afa,5ca45de909520ac243514aff`
          schema:
            type: array
              items:
                type: string
      responses:
        "200": # status code
          description: List of tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400": # status code
          description: Invalid ids.
          content:
            application/json:
              schema:
                type: object
        "404": # status code
          description: all ids not found.
          content:
            application/json:
              schema:
                type: object 
